# Use vscode Rest Client to send these requests
# Extension ID: humao.rest-client

# User Login
# Coupon
# Metrics
# Worker
# Keycloak


#################### User Login

## Create User

POST http://localhost:3000/userlogin/create
Content-Type: application/json

{
    "email": "example@mail.com",
    "password": "123pass123"
}

## Login with User

POST http://localhost:3000/userlogin/login
Content-Type: application/json

{
    "email": "example@mail.com",
    "password": "123pass123"
}


#################### Coupon

# Create coupon set

POST http://localhost:3000/coupon_set
Content-Type: application/json

{
    "name": "Campaign 1"
}

# Get single coupon

GET http://localhost:3000/coupon_set/1/coupon

# Upload coupons

POST http://localhost:3000/coupon_set/1/upload
Content-Type: application/json

[
    "39600ed3-76e5-4237-b885-0c496148c831",
    "36389d4c-46f1-4149-b570-8d4bc86d1ad1",
    "c8b8d194-bc6a-4c9c-8f7b-35ea70e4f9d1",
    "c0327618-d36f-456f-87ce-201fa9719641",
    "832af5f5-2557-41c9-9c01-266f2951adf1",
    "bb0b1199-2caa-4f89-b66e-788d9c539881",
    "a1201f5f-8313-453d-aeb3-de201e642411",
    "0dbde09e-78ec-455f-980b-798d88a93311",
    "a9a33fb2-6dfe-471e-b03d-290b9a0bafa1",
    "7bb7684f-934b-4125-9577-29dabec9b071"
]

# All set status
GET http://localhost:3000/coupon_set/status


#################### Metrics

GET http://localhost:3000/metrics


#################### Worker

PUT http://localhost:3000/worker/timeout_seconds/120


#################### Keycloak

# https://www.keycloak.org/docs-api/latest/rest-api/index.html

# Get token for admin use

POST http://localhost:8080/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin&client_id=admin-cli&grant_type=password

# Create a realm

POST http://localhost:8080/admin/realms
Authorization: bearer XX.XX.XX
Content-Type: application/json

{
    "realm": "thestack",
    "enabled": true
}

# Create a user for a realm

POST http://localhost:8080/admin/realms/thestack/users
Authorization: bearer XX.XX.XX
Content-Type: application/json

{
    "firstName": "S2S User",
    "username": "s2s_user",
    "email": "thestack@mail.com",
    "emailVerified": "true",
    "enabled": "true",
    "credentials": [
        {
            "type": "password",
            "value": "pass",
            "temporary": "false"
        }
    ]
}

# And then request credentials

POST http://localhost:8080/realms/thestack/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=s2s_user&password=pass&client_id=admin-cli&grant_type=password

# Keycloak public keys

GET http://localhost:8080/realms/thestack/protocol/openid-connect/certs
