[package]
name = "the_stack_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }

[[bin]]
name = "the_stack_client"
path = "src/main.rs"
